# semantic/samples.py
helpsample = [
    "Tôi bị đau đầu liên tục, đó có phải dấu hiệu của bệnh gì nghiêm trọng không?",
    "Tại sao tôi thường xuyên cảm thấy mệt mỏi và không có năng lượng?",
    "Tôi bị đau ngực, có phải là dấu hiệu của bệnh tim không?",
    "Tôi có triệu chứng ho kéo dài, liệu có phải tôi bị viêm phổi không?",
    "Đau bụng dưới và chu kỳ kinh nguyệt không đều có thể là dấu hiệu của vấn đề gì?",
    "Tôi bị sốt cao và ớn lạnh, có phải là bị nhiễm trùng không?",
    "Tôi bị ngứa và nổi mẩn đỏ, có phải là dấu hiệu của dị ứng không?",
    "Kết quả xét nghiệm của tôi cho thấy điều gì? Tôi cần làm gì tiếp theo?",
    "Bác sĩ chẩn đoán tôi bị [Tên bệnh], điều đó có nghĩa gì?",
    "Có phương pháp điều trị nào hiệu quả cho tình trạng của tôi không?",
    "Tôi có cần phải phẫu thuật không, và những rủi ro là gì?",
    "Nếu tôi không điều trị, bệnh của tôi có thể trở nên nghiêm trọng hơn không?",
    "Liệu thuốc mà tôi đang dùng có tác dụng phụ không?",
    "Tôi có cần thay đổi lối sống hoặc chế độ ăn uống để hỗ trợ điều trị không?",
    "Tôi có thể làm gì để ngăn ngừa bệnh này tái phát?",
    "Có cách nào để tăng cường hệ miễn dịch của tôi không?",
    "Tôi cần tiêm phòng loại vaccine nào để bảo vệ sức khỏe?",
    "Làm thế nào để tôi giữ mức cholesterol/huyết áp của mình ở mức an toàn?",
    "Tôi có cần kiểm tra sức khỏe định kỳ không? Bao lâu một lần?",
    "Tôi cảm thấy lo lắng và căng thẳng liên tục, tôi nên làm gì?",
    "Tôi bị mất ngủ, điều này có ảnh hưởng đến sức khỏe tinh thần của tôi không?",
    "Tôi cảm thấy chán nản và không muốn làm gì cả, đó có phải là trầm cảm không?",
    "Tôi cần tìm sự giúp đỡ ở đâu nếu tôi gặp vấn đề về sức khỏe tâm thần?",
    "Làm thế nào để biết tôi có mắc bệnh tiểu đường hay không?",
    "Bệnh tăng huyết áp là gì và tôi cần làm gì để kiểm soát?",
    "Ung thư có những triệu chứng gì ban đầu? Tôi cần làm xét nghiệm nào để phát hiện sớm?",
    "Bệnh tim mạch là gì và làm thế nào để phòng ngừa?"
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]
